### PR TITLE
feat: Allow iterating over `LocationSegment`'s from a `Location`

### PR DESCRIPTION
**Pull request by gmpinder**
I've been working on improving validation for [BlueBuild](https://github.com/blue-build)'s recipe format, and the way we do that is to find the byte offset in the file via the location specified by the errors reported by this crate. We need to iterate over the segments of the `Location` object so that we can follow the AST in the Yaml parser. We created our own wrapper around `Location` to have this support, but we'd like to have this available upstream for other's to use.

### CODE REVIEW

**Comment by Stranger6667** [comment]
Thank you @gmpinder ! And sorry as I promised to add this and completely forgot to go through my todo list for jsonschema. I had a few thoughts about location - will add them in a separate comment a bit later.

**Comment by gmpinder** [comment]
> Thank you @gmpinder ! And sorry as I promised to add this and completely forgot to go through my todo list for jsonschema. I had a few thoughts about location - will add them in a separate comment a bit later.

It's all good @Stranger6667 ! I completely understand getting caught up in other things, especially in the lead up to the new year.

**Comment by Stranger6667** [comment]
Good! I am going to merge this, and then in a separate PR will add some tests / docs, perf + make use of it in Python bindings. Thank you for contributing!

**Comment by gmpinder** [comment]
> Good! I am going to merge this, and then in a separate PR will add some tests / docs, perf + make use of it in Python bindings. Thank you for contributing!

Glad to help contribute!

**Comment by Stranger6667** [comment]
Released in 0.28.0 :)

**Comment by gmpinder** [comment]
> Released in 0.28.0 :)

Awesome thanks!

**Pull request merged**
